Strek4Mayor/Models/QandA.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Strek4Mayor.Models
{
    public class QandA
    {
        public int QandAId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }
        [Display(Name = "Question")]
        public string Body { get; set; }
        [Display(Name = "Topic (optional)")]
        public string Title { get; set; }
        public string Answer { get; set; }
        [Display(Name = "Answered")]
        public bool MessageStatus { get; set; }
        [Display(Name = "Your name (optional)")]
        public string Member { get; set; }
    }
}

Strek4Mayor/Controllers/QandAController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Strek4Mayor.Models;
using BotDetect.Web.Mvc;

namespace Strek4Mayor.Controllers
{
    public class QandAController : Controller
    {
        private Strek4MayorContext db = new Strek4MayorContext();

        // GET: /QandA/
        public ActionResult Search(string searchString)
        {
            var search = db.QandAs.Where(s => s.Body.Contains(searchString));
            //return View(db.QandAs.ToList());
            return View(search);
        }

        public ActionResult Thanks()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View(db.QandAs.ToList());
        }

        public ActionResult AjaxIndex()
        {
            return PartialView(db.QandAs.ToList());
        }

        // GET: /QandA/
        [Authorize(Roles = "Admin")]
        public ActionResult Admin()
        {
            return View(db.QandAs.ToList());
        }

        // GET: /QandA/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QandA qanda = db.QandAs.Find(id);
            if (qanda == null)
            {
                return HttpNotFound();
            }
            return View(qanda);
        }

        public static class CaptchaHelper
        {
            public static MvcCaptcha GetExampleCaptcha()
            {
                // create the control instance
                MvcCaptcha exampleCaptcha = new MvcCaptcha("Create");

                // set up client-side processing of the Captcha code input textbox
                exampleCaptcha.UserInputID = "Create";

                return exampleCaptcha;
            }
        }

        // GET: /QandA/Create
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: /QandA/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        [CaptchaValidation("CaptchaCode", "ExampleCaptcha", "Incorrect CAPTCHA code!")]
        public ActionResult Create([Bind(Include="QandAId,Body,Title,Member")] QandA qanda, bool captchavalid)
        {
            if (ModelState.IsValid)
            {
                qanda.Date = DateTime.Now;
                qanda.MessageStatus = false;
                MvcCaptcha.ResetCaptcha("ExampleCaptcha");
                db.QandAs.Add(qanda);
                db.SaveChanges();
                return RedirectToAction("Thanks");
            }
            else
            {
                MvcCaptcha.IsCaptchaSolved("Incorrect CAPTCHA code!");
                ViewBag.ErrMessage = "Error: captcha is not valid."; 
            }

            return View(qanda);
        }

        // GET: /QandA/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QandA qanda = db.QandAs.Find(id);
            if (qanda == null)
            {
                return HttpNotFound();
            }
            return View(qanda);
        }

        // POST: /QandA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="QandAId,Member,Date,Body,Title,Answer,MessageStatus")] QandA qanda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qanda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(qanda);
        }

        // GET: /QandA/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Answer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QandA qanda = db.QandAs.Find(id);
            if (qanda == null)
            {
                return HttpNotFound();
            }
            return View(qanda);
        }

        // POST: /QandA/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Answer([Bind(Include = "Member,Title,Body,Answer")] QandA qanda, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (ModelState.IsValid)
            {
                var findQuestion = db.QandAs.Find(id);
                findQuestion.Answer = qanda.Answer;
                findQuestion.MessageStatus = true;
                db.Entry(findQuestion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Admin");
            }
            return View(qanda);
        }

        // GET: /QandA/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QandA qanda = db.QandAs.Find(id);
            if (qanda == null)
            {
                return HttpNotFound();
            }
            return View(qanda);
        }

        // POST: /QandA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QandA qanda = db.QandAs.Find(id);
            db.QandAs.Remove(qanda);
            db.SaveChanges();
            return RedirectToAction("Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Strek4Mayor/Views/QandA/Admin.cshtml
@model IEnumerable<Strek4Mayor.Models.QandA>
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>   
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.MessageStatus == false) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)

            </td>
            <td>
                @Html.ActionLink("Answer", "Answer", new { id = item.QandAId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.QandAId })
            </td>
        </tr>
        }
    }

</table>
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/AjaxIndex.cshtml
@model IEnumerable<Strek4Mayor.Models.QandA>

<style>
    .question-box {
        background-color: #EEE8AA;
        border: 1px solid #D2B48C;
        margin-top: 2vh;
        padding: 15px;
    }
    .question-box hr {
        height: 1px;
        margin: 2vh 2vw;
        background: #D2B48C;
    }
    #submit:hover {
        background-color: lightblue;
    }
</style>
      <p>
      <input type="button" id="submit" style='width:300px' value="Ask Me a Question" onclick="location.href='@Url.Action("Create", "QandA")'" />
      <br />
         @if (User.IsInRole("Admin"))
             {
                using (Html.BeginForm("Search", "QandA", FormMethod.Post))
                {
                    @Html.TextBox("SearchString"); <br />
                    <input type="submit" value="Search" />
                }
             }
             
      </p>

@foreach (var item in Model)
{
    if (item.MessageStatus == true)
    {
        <div class="question-box">
            @Html.Label("Question: ")
            @{
                var paragraphs = item.Body.Replace("\r\n", "<br />").Replace("\n", "<br />").Replace("\r", "<br />");
            }
            @Html.Raw(paragraphs)
            <br />
            @Html.Label("Asked by: ")
            @Html.DisplayFor(modelItem => item.Member)
            @Html.Name(" on ")
            @Html.DisplayFor(modelItem => item.Date)
            <br />
            @if (item.Title!="") {
                @Html.Label("Topic: ")
                @Html.DisplayFor(modelItem => item.Title)
            }
            <hr />
            @Html.Label("Answer: ")
            @{
                paragraphs = item.Answer.Replace("\r\n", "<br />").Replace("\n", "<br />").Replace("\r", "<br />");
            }
            @Html.Raw(paragraphs)
               
            @if (User.IsInRole("Admin"))
            {
                    @Html.ActionLink("Edit", "Edit", new { id = item.QandAId })
                    @Html.Name(" | ")
                    @Html.ActionLink("Details", "Details", new { id = item.QandAId })
                    @Html.Name(" | ")
                    @Html.ActionLink("Delete", "Delete", new { id = item.QandAId })
            }
        </div>
    }
}

Strek4Mayor/Views/QandA/Answer.cshtml
@model Strek4Mayor.Models.QandA
@{
    ViewBag.Title = "Answer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Answer</h2>

<div>
    <h4>QandA</h4>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Member)
            </dt>
            <dd>
                @Html.EditorFor(model => model.Member)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.EditorFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Body)
            </dt>
            <dd>
                @Html.TextAreaFor(model => model.Body, 5, 50, null)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Answer)
            </dt>
            <dd>
                @Html.TextAreaFor(model => model.Answer, 5, 50, null)
                @Html.ValidationMessageFor(model => model.Answer)
            </dd>
        </dl>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    }
    <script>
    $('.tile-6').addClass('highlighted');
    </script>

Strek4Mayor/Views/QandA/Create.cshtml
@model Strek4Mayor.Models.QandA
@using BotDetect.Web.Mvc;

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>Ask</title>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/QandA.css")" />
</head>


    

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" id="captcha-box">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Member, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Member)
                @Html.ValidationMessageFor(model => model.Member)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 5, 50, null)
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>
        
            <link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl"
                  rel="stylesheet" type="text/css" />
            @Html.Label("CaptchaCode", "Retype the code from the picture")
            @{ MvcCaptcha exampleCaptcha = new MvcCaptcha("ExampleCaptcha");
             exampleCaptcha.UserInputID = "CaptchaCode";}
            @Html.Captcha(exampleCaptcha)
            @Html.TextBox("CaptchaCode")
            <p class="Error">  @ViewBag.ErrMessage </p>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<!--exampleCaptcha = CaptchaHelper.GetExampleCaptcha()-->
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/Delete.cshtml
@model Strek4Mayor.Models.QandA

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QandA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>       
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/Details.cshtml
@model Strek4Mayor.Models.QandA

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>QandA</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MessageStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MessageStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QandAId }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/Edit.cshtml
@model Strek4Mayor.Models.QandA

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QandA</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.QandAId)

        <div class="form-group">
            @Html.LabelFor(model => model.Member, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Member)
                @Html.ValidationMessageFor(model => model.Member)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, 5, 50, null)
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Answer, 5, 50, null)
                @Html.ValidationMessageFor(model => model.Answer)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MessageStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MessageStatus)
                @Html.ValidationMessageFor(model => model.MessageStatus)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/Index.cshtml
@model IEnumerable<Strek4Mayor.Models.QandA>

@{
    ViewBag.Title = "Q and A";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("AjaxIndex") 
<script>
    $('.tile-6').addClass('highlighted');
</script>

Strek4Mayor/Views/QandA/Search.cshtml
@model IEnumerable<Strek4Mayor.Models.QandA>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>


@Html.Partial("AjaxIndex")

Strek4Mayor/Views/QandA/Thanks.cshtml
@model Strek4Mayor.Models.QandA

@{
    ViewBag.Title = "Thanks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<meta http-equiv="refresh" content="10; url= ~/QandA/Index">
<h2 style="color:red;">Thank for your question. Once reviewed your question will be answered as soon as possible. You will be redirected in 10 seconds</h2></br>
<input type="button" id="submit" style='width:300px' value="return to Question page" onclick="location.href='@Url.Action("Index", "QandA")'" /> 

<script>
    $('.tile-6').addClass('highlighted');
</script>